### ISSUE TITLE
Can you add documentation on using Ebsynth from this repo?

### ISSUE THREAD

**Issue by psurya1994** [dcharata/StyLit#36]
I see in your readme that Ebsynth has been implemented in the master branch. But I'm unable to any instructions on the usage, adding it would be of great help.

**Comment by vikasTmz** [comment]
We provide instructions to do so here: https://github.com/dcharata/StyLit#overview-of-program. It is a matter of just changing the hyper-parameters.

If you are referring to the [video stylization work from the same authors](https://dcgi.fel.cvut.cz/home/sykorad/ebsynth.html), then this repository doesn't implement that. Please check out this repository from our friends at Brown: https://github.com/ctrotz/stylizing-video.

**Comment by psurya1994** [comment]
That's helpful information, thanks Vikas! :)
